name:  DEV setup
on:
  push:
    branches:
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    -uses:actions/checkout@v1
          DEPLOY_KEY: ${{ secrets.ZAPPY_PEM }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: 22
          FOLDER: test/*
          SERVER_IP: ${{ secrets.ZAPPY_IP }}
          USERNAME: ubuntu
          SERVER_DESTINATION: /var/www/test
          
